### ISSUE TITLE
Do not export `all_means`

### ISSUE THREAD

**Issue by carstenbauer** [ffreyer/BinningAnalysis.jl#4]
The means on all levels should be exactly identical (up to rounding erros), right?

**Comment by ffreyer** [comment]
Not quite, some values are lost as you move down the binning levels, since only multiples of 2 can propagate. For example, if you push 101 values, level 0 will have the mean of all of them, level 1 the mean of 100 (50 bins), then 100 (25 bins), then 96 (12 bins), etc. If the binning analysis converged they should be identical up to statistical errors, with level 0 being the most accurate.
I think it's fine to remove this.

**Comment by carstenbauer** [comment]
Indeed.
